In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import nltk
nltk.download(["names","stopwords","state_union","twitter_samples","movie_reviews","averaged_perceptron_tagger","vader_lexicon","punkt",])

[nltk_data] Downloading package names to /root/nltk_data...
[nltk_data]   Package names is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package state_union to /root/nltk_data...
[nltk_data]   Package state_union is already up-to-date!
[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
from nltk.tokenize import word_tokenize
import string
def process_text(text):
  tokens = word_tokenize(text)
  tokens = [w.lower() for w in tokens]
  re_punc = re.compile('[%s]' % re.escape(string.punctuation))
  stripped = [re_punc.sub('', w) for w in tokens]
  words = [word for word in stripped if word.isalpha()]
  words = [w for w in words if not w in stopwords.words('english')]
  words=' '.join(words)
  return words

In [ ]:
from google.colab import files
up = files.upload()

Saving amazon_review.csv to amazon_review (1).csv

In [ ]:
iph = pd.read_csv('amazon_review.csv')
iph = iph.drop('Unnamed: 0',axis=1)
iph

               Customer  ...                                        Review Body
0       S.Siva Ram Kris  ...    Worst battery performance.Iphone 11 is far b...
1          Tarun barath  ...    Your browser does not support HTML5 video.  ...
2          Tarun barath  ...    This was my first switch to an ios device af...
3       S.Siva Ram Kris  ...    Sold kidney bought this, now not feeling wel...
4                 Paras  ...    My girlfriend demanded me this iphone... And...
..                  ...  ...                                                ...
350    Manash Choudhury  ...       It’s apple. What else reason do by you need?
351  Zilangamba warepam  ...    Overall good but camera and battery life not...
352              Kinjol  ...    Given a 1 Star as Apple continues to sell a ...
353   A.Selvamanikandan  ...    Order was Apple iPhone 12 dated 9/4/21 item ...
354         Sumit vansh  ...               Price is of brand only ,nothing else

[355 rows x 5 columns]

In [ ]:
iph.isnull().any()

Customer        False
Date            False
Rating          False
Review Title    False
Review Body     False
dtype: bool

In [ ]:
iph['Review Body'] = iph['Review Body'].apply(process_text)
iph['Review Title'] = iph['Review Title'].apply(process_text)

In [ ]:
iph

               Customer  ...                                        Review Body
0       S.Siva Ram Kris  ...  worst battery performanceiphone far better den...
1          Tarun barath  ...  browser support video another beauty apple upg...
2          Tarun barath  ...  first switch ios device using android untill d...
3       S.Siva Ram Kris  ...  sold kidney bought feeling well number days al...
4                 Paras  ...  girlfriend demanded iphone uploading pics new ...
..                  ...  ...                                                ...
350    Manash Choudhury  ...                             apple else reason need
351  Zilangamba warepam  ...       overall good camera battery life good iphone
352              Kinjol  ...  given star apple continues sell defective prod...
353   A.Selvamanikandan  ...  order apple iphone dated item received opening...
354         Sumit vansh  ...                           price brand nothing else

[355 rows x 5 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow1=CountVectorizer().fit_transform(iph['Review Title']).toarray()
bow2=CountVectorizer().fit_transform(iph['Review Body']).toarray()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(bow1,iph['Rating'],test_size=0.5)
from sklearn.naive_bayes import MultinomialNB
mnclassifier = MultinomialNB().fit(X_train, y_train)
xtrain,xtest,ytrain,ytest= train_test_split(bow2,iph['Rating'],test_size=0.5)
mnclassifier1 = MultinomialNB().fit(xtrain, ytrain)

In [ ]:
predict = mnclassifier.predict(bow1)
predict1 = mnclassifier1.predict(bow2)

In [ ]:
iphrate = pd.DataFrame()
iphrate['title'] = predict
iphrate['body'] = predict1

In [ ]:
iphrate['avg'] = ""

In [ ]:
for i in range(len(iphrate['title'])):
  iphrate['avg'][i]=round((int(iphrate['title'][i])+int(iphrate['body'][i]))/2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
iphrate

     title  body avg
0      5.0   5.0   5
1      3.0   5.0   4
2      5.0   5.0   5
3      3.0   5.0   4
4      5.0   3.0   4
..     ...   ...  ..
350    5.0   5.0   5
351    5.0   5.0   5
352    5.0   5.0   5
353    5.0   5.0   5
354    5.0   5.0   5

[355 rows x 3 columns]

In [ ]:
iph['New Rating'] = iphrate['avg']

In [ ]:
iph

               Customer  ... New Rating
0       S.Siva Ram Kris  ...          5
1          Tarun barath  ...          4
2          Tarun barath  ...          5
3       S.Siva Ram Kris  ...          4
4                 Paras  ...          4
..                  ...  ...        ...
350    Manash Choudhury  ...          5
351  Zilangamba warepam  ...          5
352              Kinjol  ...          5
353   A.Selvamanikandan  ...          5
354         Sumit vansh  ...          5

[355 rows x 6 columns]

In [ ]:
from google.colab import files
up = files.upload()

Saving samsung_a31.csv to samsung_a31.csv

In [ ]:
sams = pd.read_csv('samsung_a31.csv')
sams = sams.drop('Unnamed: 0',axis=1)
sams

                 Customer  ...                                        Review Body
0                      VM  ...    Network issue on this phoneCalls not get con...
1                  sajjad  ...    Very nice lots of features.manufactred in In...
2                  gaurav  ...    I don't think it will be a nice decision to ...
3                    Seri  ...    The phone is good...battery is excellent..it...
4       Bibaswan Banerjee  ...    Speed is not upto the mark as 6GB RAM phone ...
..                    ...  ...                                                ...
451           Saurav Guha  ...                                                NaN
452           Varun Sodhi  ...                                                NaN
453            ajay sehta  ...                                                NaN
454       Amazon Customer  ...                                                NaN
455  Dipankar Chakrabarti  ...                                                NaN

[456 rows x 5 columns]

In [ ]:
sams = sams.dropna()
sams

              Customer  ...                                        Review Body
0                   VM  ...    Network issue on this phoneCalls not get con...
1               sajjad  ...    Very nice lots of features.manufactred in In...
2               gaurav  ...    I don't think it will be a nice decision to ...
3                 Seri  ...    The phone is good...battery is excellent..it...
4    Bibaswan Banerjee  ...    Speed is not upto the mark as 6GB RAM phone ...
..                 ...  ...                                                ...
375    Himanshu Baluni  ...    excellant. Loved the phone and the battery b...
376        Anant revar  ...    Its Very Good Phone By Samsung Just One Word...
377             Jai H.  ...    nice battery life and perfect big screen for...
378     Pandava Swetha  ...                                  Good battery life
379             Satvik  ...                                       Good overall

[380 rows x 5 columns]

In [ ]:
sams.isnull().any()

Customer        False
Date            False
Rating          False
Review Title    False
Review Body     False
dtype: bool

In [ ]:
sams['Review Body'] = sams['Review Body'].apply(process_text)
sams['Review Title'] = sams['Review Title'].apply(process_text)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
sams

              Customer  ...                                        Review Body
0                   VM  ...  network issue phonecalls get connected restart...
1               sajjad  ...                      nice lots featuresmanufactred
2               gaurav  ...  nt think nice decision purchase product produc...
3                 Seri  ...  phone good battery excellentits response also ...
4    Bibaswan Banerjee  ...  speed upto mark ram phone expected samsung out...
..                 ...  ...                                                ...
375    Himanshu Baluni  ...                 excellant loved phone battery back
376        Anant revar  ...  good phone samsung one word feedback amazing p...
377             Jai H.  ...        nice battery life perfect big screen movies
378     Pandava Swetha  ...                                  good battery life
379             Satvik  ...                                       good overall

[380 rows x 5 columns]

In [ ]:
bow1=CountVectorizer().fit_transform(sams['Review Title']).toarray()
bow2=CountVectorizer().fit_transform(sams['Review Body']).toarray()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(bow1,sams['Rating'],test_size=0.5)
from sklearn.naive_bayes import MultinomialNB
mnclassifier = MultinomialNB().fit(X_train, y_train)
xtrain,xtest,ytrain,ytest= train_test_split(bow2,sams['Rating'],test_size=0.5)
mnclassifier1 = MultinomialNB().fit(xtrain, ytrain)

In [ ]:
predict = mnclassifier.predict(bow1)
predict1 = mnclassifier1.predict(bow2)

In [ ]:
samsrate = pd.DataFrame()
samsrate['title'] = predict
samsrate['body'] = predict1
samsrate['avg'] = ""

In [ ]:
for i in range(len(samsrate['title'])):
  samsrate['avg'][i]=round((int(samsrate['title'][i])+int(samsrate['body'][i]))/2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
samsrate

     title  body avg
0      5.0   1.0   3
1      5.0   1.0   3
2      1.0   1.0   1
3      5.0   1.0   3
4      1.0   1.0   1
..     ...   ...  ..
375    1.0   5.0   3
376    5.0   5.0   5
377    5.0   5.0   5
378    5.0   5.0   5
379    5.0   5.0   5

[380 rows x 3 columns]

In [ ]:
sams['New Rating'] = samsrate['avg']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
sams

              Customer  ... New Rating
0                   VM  ...          3
1               sajjad  ...          3
2               gaurav  ...          1
3                 Seri  ...          3
4    Bibaswan Banerjee  ...          1
..                 ...  ...        ...
375    Himanshu Baluni  ...          3
376        Anant revar  ...          5
377             Jai H.  ...          5
378     Pandava Swetha  ...          5
379             Satvik  ...          5

[380 rows x 6 columns]

In [ ]:
sams.to_csv('samsung_new_rating_data.csv')
iph.to_csv('iphone_new_rating_data.csv')